#################################################################################################################
## LIGHTS ##
#################################################################################################################
- alias: Turn on both stair lights to 100% from 0430-1030pm
  trigger:
    platform: state
    entity_id: binary_sensor.2nd_floor_motion_sensor_sensor
    to: 'on'
  condition:
    condition: time
    after: '16:30:00'
    before: '22:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.lower_stair_lights_level, light.upper_stair_lights_level
        brightness: 230

- alias: Turn on both stair lights to 40% from 1030pm-0700am
  trigger:
    platform: state
    entity_id: binary_sensor.2nd_floor_motion_sensor_sensor
    to: 'on'
  condition:
    condition: time
    after: '22:30:00'
    before: '07:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.lower_stair_lights_level, light.upper_stair_lights_level
        brightness: 102

- alias: Turn off both stair lights after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.2nd_floor_motion_sensor_sensor
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    entity_id: light.lower_stair_lights_level, light.upper_stair_lights_level


- alias: Turn on upper stair lights to 100% from 430-1030pm
  trigger:
  - platform: state
    entity_id: binary_sensor.3rd_floor_motion_sensor_sensor
    to: 'on'
  condition:
    condition: time
    after: '16:30:00'
    before: '22:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.upper_stair_lights_level
        brightness: 230

- alias: Turn on upper stair lights to 40% from 1030-0700am
  trigger:
  - platform: state
    entity_id: binary_sensor.3rd_floor_motion_sensor_sensor
    to: 'on'
  condition:
    condition: time
    after: '22:30:00'
    before: '07:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.upper_stair_lights_level
        brightness: 102

- alias: Turn off upper stair lights after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.3rd_floor_motion_sensor_sensor
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    entity_id: light.upper_stair_lights_level

- alias: Turn on lower stair lights to 100% from 0430-1030pm
  trigger:
    platform: state
    entity_id: binary_sensor.centralite_3326l_0b5c4027_1
    to: 'on'
  condition:
    condition: time
    after: '16:30:00'
    before: '22:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.lower_stair_lights_level
        brightness: 230

- alias: Turn on lower stair lights to 40% from 1030-0700am
  trigger:
    platform: state
    entity_id: binary_sensor.centralite_3326l_0b5c4027_1
    to: 'on'
  condition:
    condition: time
    after: '22:30:00'
    before: '07:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.lower_stair_lights_level
        brightness: 102

- alias: Turn off lower stair lights after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.centralite_3326l_0b5c4027_1
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    entity_id: light.lower_stair_lights_level

#################################################################################################################
## MISC ##
#################################################################################################################

- alias: SSL expiry notification
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
  action:
    service: notify.ios_vaibhavs_iphone
    data:
      message: Warning - SSL certificate expires in 21 days and has not been automatically renewed


- alias: Auto Renew SSL Cert
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl

- alias: Home Assistant update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.ios_vaibhavs_iphone
    data:
      message: 'There is a new Home Assistant release available.'

#################################################################################################################
## ANNOUNCEMENTS ##
#################################################################################################################

- alias: Doorbell Ding Announcement
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_ding
      from: 'off'
      to: 'on'
  action:
   - service: tts.google_say
     data:
       entity_id: media_player.living_room_speaker, media_player.bedroom_speaker
       message: Someone is at the door!

- alias: Doorbell Motion Announcement
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      from: 'off'
      to: 'on'
  action:
   - service: tts.google_say
     data:
       entity_id: media_player.living_room_speaker, media_player.bedroom_speaker
       message: Motion detected. Someone may be at the front door!

- alias: Alpesh has left home
  trigger:
    - platform: state
      entity_id: device_tracker.alpeshs_iphone
      from: 'home'
      to: 'not_home'
  action:
   - service: notify.ios_vaibhavs_iphone
     data:
       message: Alpesh has left home.

- alias: Alpesh has arrived home
  trigger:
    - platform: state
      entity_id: device_tracker.alpeshs_iphone
      from: 'not_home'
      to: 'home'
  action:
   - service: notify.ios_vaibhavs_iphone
     data:
       message: Alpesh has arrived home.

- alias: Parul has left home
  trigger:
    - platform: state
      entity_id: device_tracker.paruls_iphone
      from: 'home'
      to: 'not_home'
  action:
   - service: notify.ios_vaibhavs_iphone
     data:
       message: Parul has left home.

- alias: Parul has arrived home
  trigger:
    - platform: state
      entity_id: device_tracker.paruls_iphone
      from: 'not_home'
      to: 'home'
  action:
   - service: notify.ios_vaibhavs_iphone
     data:
       message: Parul has arrived home.

- alias: Alpesh is at mandir
  trigger:
    platform: zone
    entity_id: device_tracker.alpeshs_iphone
    zone: zone.mandir
    event: enter
  action:
   - service: notify.ios_vaibhavs_iphone
     data:
       message: Alpesh is at mandir.

- alias: Alpesh has left mandir
  trigger:
    platform: zone
    entity_id: device_tracker.alpeshs_iphone
    zone: zone.mandir
    event: leave
  action:
   - service: notify.ios_vaibhavs_iphone
     data:
       message: Alpesh has left mandir.

- alias: Vaibhav has arrived at school
  trigger:
    platform: zone
    entity_id: device_tracker.vaibhavs_iphone
    zone: zone.school
    event: enter
  action:
   - service: notify.ios_vaibhavs_iphone
     data:
       message: Vaibhav has arrived at school.

- alias: Keep Google Home Alive - Bedroom Speaker
  trigger:
    platform: time
    minutes: '/2'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.bedroom_speaker
        state: 'off'
      - condition: state
        entity_id: media_player.bedroom_speaker
        state: 'idle'
  action:
    service: media_player.play_media
    entity_id: media_player.bedroom_speaker
    data:
      media_content_id: https://hassio.local:8123/local/audio/1sec.mp3
      media_content_type: music

- alias: Keep Google Home Alive - Living Room Speaker
  trigger:
    platform: time
    minutes: '/2'
    seconds: 00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.living_room_speaker
        state: 'off'
      - condition: state
        entity_id: media_player.living_room_speaker
        state: 'idle'
  action:
    service: media_player.play_media
    entity_id: media_player.living_room_speaker
    data:
      media_content_id: https://hassio.local:8123/local/audio/1sec.mp3
      media_content_type: music

- alias: Motion on Second Floor - Notification
  trigger:
    platform: state
    entity_id: binary_sensor.2nd_floor_motion_sensor_sensor
    to: 'on'
  action:
    - service:  media_player.volume_set
      entity_id: media_player.bedroom_speaker
      data:
        volume_level: 1
    - service:  media_player.play_media
      data:
        entity_id: media_player.bedroom_speaker
        media_content_id: https://tankv.duckdns.org/local/audio/Chime.mp3
        media_content_type: audio/mp3
    - service:  media_player.volume_set
      entity_id: media_player.bedroom_speaker
      data:
        volume_level: 0.3

- alias: Dog Bark
  trigger:
    platform: state
    entity_id: binary_sensor.ring_front_door_motion
    to: 'on'
  condition:
    condition: time
    after: '16:30:00'
    before: '11:59:00'
    condition: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
    - service:  media_player.volume_set
      entity_id: media_player.living_room_speaker
      data:
        volume_level: 1
    - service:  media_player.play_media
      data:
        entity_id: media_player.living_room_speaker
        media_content_id: https://tankv.duckdns.org/local/audio/DogBark.mp3
        media_content_type: audio/mp3

###################################
##  cuckoo Clock simulation.
## Plays the number of cuckoos per hour and 1 on the half hour.
###################################

# - alias: Cuckoo Clock
#   trigger:
#     - platform: time
#       minutes: 00
#       seconds: 20
#     - platform: time
#       minutes: 30
#       seconds: 00
#   condition:
#     - condition: template
#       value_template: >
#         {% if is_state('media_player.living_room_speaker', 'playing') %}
#           false
#         {% else %}
#           true
#         {% endif %}
#   action:
#     - service: media_player.turn_on
#       entity_id: media_player.living_room_speaker
#     - service: media_player.volume_set
#       entity_id:
#         - media_player.living_room_speaker
#       data:
#         volume_level: 1
#     - service: media_player.play_media
#       data_template:
#         entity_id:
#           - media_player.living_room_speaker
#         #  - media_player.bedroom_alarm_panel
#         media_content_id: >
#           {% if now().strftime("%M")|int == 30 %}
#           https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/sounds/cuckoo-clock-01.wav
#           {% else %}
#           https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/sounds/cuckoo-clock-{{now().strftime("%I")}}.wav
#           {% endif %}
#         media_content_type: audio/mp4

- alias: Heal ZWave Nightly
  trigger:
    platform: time
    at: '12:00:00'
  action:
    - service: zwave.heal_network

- alias: Heal Node 11
  trigger:
    platform: state
    entity_id: zwave.upper_stair_lights
    to: 'dead'
  action:
    - service: zwave.heal_node
      data:
        node_id: 11
    - service: homeassistant.restart
    - service: notify.ios_vaibhavs_iphone
      data:
       message: Node 11 was healed.

- alias: Heal Node 5
  trigger:
    platform: state
    entity_id: zwave.lower_stair_lights
    to: 'dead'
  action:
    - service: zwave.heal_node
      data:
        node_id: 5
    - service: homeassistant.restart
    - service: notify.ios_vaibhavs_iphone
      data:
       message: Node 5 was healed.















